version: '3.8'

services:
  db:
    container_name: ayomi_bdd
    image: "postgres"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=ayomi
      - POSTGRES_USER=ayomi
      - POSTGRES_PASSWORD=ayomi
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: always
    networks:
      - test-ayomi
  api:
    container_name: ayomi_api
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=ayomi
      - POSTGRES_USER=ayomi
      - POSTGRES_PASSWORD=ayomi
    depends_on:
      - db
    restart: always
    networks:
      - test-ayomi
  front:
    container_name: ayomi_gui
    image: app-dev
    build:
      context: ./gui
      dockerfile: Dockerfile.gui
    command: npm start
    restart: always
    volumes:
      - ./gui:/app
    ports:
      - 3000:3000
networks:
  test-ayomi:
